name = "nomad-magazine"
main = "dist/_worker.js"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "nomad-magazine.com/*", zone_name = "nomad-magazine.com" },
  { pattern = "www.nomad-magazine.com/*", zone_name = "nomad-magazine.com" }
]

[observability]
enabled = true

[vars]
SMART_SUITE_APIKEY = "SMART_SUITE_APIKEY_PLACEHOLDER"
SMART_SUITE_ACCOUNT_ID = "SMART_SUITE_ACCOUNT_ID_PLACEHOLDER"
SMART_SUITE_TABLE_ID_COMPANY = "SMART_SUITE_TABLE_ID_COMPANY_PLACEHOLDER"
OPENAI_API_KEY = "OPENAI_API_KEY_PLACEHOLDER"
STRIPE_SECRET_KEY = "STRIPE_SECRET_KEY_PLACEHOLDER"
STRIPE_WEBHOOK_SECRET = "STRIPE_WEBHOOK_SECRET_PLACEHOLDER"
BENTO_SITE_UUID = "BENTO_SITE_UUID_PLACEHOLDER"
BENTO_PUBLISHABLE_KEY = "BENTO_PUBLISHABLE_KEY_PLACEHOLDER"
BENTO_SECRET_KEY = "BENTO_SECRET_KEY_PLACEHOLDER"
