name = "nomad-magazine"
main = "dist/_worker.js"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[route]
pattern = "nomad-magazine.com"
custom_domain = true

[vars]
OPENAI_API_KEY = "OPENAI_API_KEY_PLACEHOLDER"
STRIPE_SECRET_KEY = "STRIPE_SECRET_KEY_PLACEHOLDER"
STRIPE_WEBHOOK_SECRET = "STRIPE_WEBHOOK_SECRET_PLACEHOLDER"
BENTO_SITE_UUID = "BENTO_SITE_UUID_PLACEHOLDER"
BENTO_PUBLISHABLE_KEY = "BENTO_PUBLISHABLE_KEY_PLACEHOLDER"
BENTO_SECRET_KEY = "BENTO_SECRET_KEY_PLACEHOLDER"
