name = "nomad-horoscope"
main = "index.js"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
tsconfig = "tsconfig.json"

[observability]
enabled = true

[route]
pattern = "horoscope.nomad-magazine.com"
custom_domain = true

[vars]
OPENAI_API_KEY = { type = "secret" } 
