name: Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
        env:
          BENTO_SITE_UUID: ${{ secrets.BENTO_SITE_UUID }}
          BENTO_SECRET_KEY: ${{ secrets.BENTO_SECRET_KEY }}
          BENTO_PUBLISHABLE_KEY: ${{ secrets.BENTO_PUBLISHABLE_KEY }}
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
      - name: Set branch name
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            ref=${{ github.event.pull_request.head.ref }}
            if [ "$ref" == "refs/heads/main" ]; then
              echo "branch=main" >> $GITHUB_OUTPUT
            else
              echo "branch=${ref}" >> $GITHUB_OUTPUT
            fi
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi
      - name: Deploy to Cloudflare Workers
        id: deploy
        run: |
          echo "" >> wrangler.toml
          echo "[vars]" >> wrangler.toml
          echo "BENTO_SITE_UUID = \"${{ secrets.BENTO_SITE_UUID }}\"" >> wrangler.toml
          echo "BENTO_SECRET_KEY = \"${{ secrets.BENTO_SECRET_KEY }}\"" >> wrangler.toml
          echo "BENTO_PUBLISHABLE_KEY = \"${{ secrets.BENTO_PUBLISHABLE_KEY }}\"" >> wrangler.toml
          echo "SMART_SUITE_APIKEY = \"${{ secrets.SMART_SUITE_APIKEY }}\"" >> wrangler.toml
          echo "SMART_SUITE_ACCOUNT_ID = \"${{ secrets.SMART_SUITE_ACCOUNT_ID }}\"" >> wrangler.toml
          echo "SMART_SUITE_TABLE_ID_COMPANY = \"${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}\"" >> wrangler.toml
          output=$(bunx wrangler@latest deploy --env ${{ steps.vars.outputs.branch }})
          echo "$output"
          url=$(echo "$output" | grep -o 'https://[^[:space:]]*\.workers\.dev' | head -1)
          echo "deployment_url=$url" >> $GITHUB_OUTPUT
        env:
          BENTO_SITE_UUID: ${{ secrets.BENTO_SITE_UUID }}
          BENTO_SECRET_KEY: ${{ secrets.BENTO_SECRET_KEY }}
          BENTO_PUBLISHABLE_KEY: ${{ secrets.BENTO_PUBLISHABLE_KEY }}
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Comment deployed link on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = '${{ steps.deploy.outputs.deployment_url }}';
            if (deploymentUrl) {
              const body = `🚀 Preview deployed: [${deploymentUrl}](${deploymentUrl})`;
              await github.rest.issues.createComment({
                body,
                repo: context.repo.repo,
                owner: context.repo.owner,
                issue_number: context.issue.number,
              });
            }
