name: Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'cloudflare_workers/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'cloudflare_workers/**'
      - '.github/workflows/deploy-workers.yml'
  repository_dispatch:
    types: [sync-deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - name: Set branch name
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            ref=${{ github.event.pull_request.head.ref }}
            if [ "$ref" == "refs/heads/main" ]; then
              echo "branch=main" >> $GITHUB_OUTPUT
            else
              echo "branch=${ref}" >> $GITHUB_OUTPUT
            fi
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi
      - name: Deploy to Cloudflare Workers
        id: deploy
        run: |
          output=$(bunx wrangler@latest deploy)
          echo "$output"
          url=$(echo "$output" | grep -o 'https://[^[:space:]]*\.workers\.dev' | head -1)
          echo "deployment_url=$url" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Comment deployed link on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = '${{ steps.deploy.outputs.deployment_url }}';
            if (deploymentUrl) {
              const body = `Preview:\n[${deploymentUrl}](${deploymentUrl})`;
              await github.rest.issues.createComment({
                body,
                repo: context.repo.repo,
                owner: context.repo.owner,
                issue_number: context.issue.number,
              });
            }
