name: Sync Directory from Smart suite

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-directory]

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove cached directory JSONs
        run: find . -name "*directory_cache*.json" -type f -delete
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build project (regenerate cache)
        run: bun run build
        env:
          BENTO_SITE_UUID: ${{ secrets.BENTO_SITE_UUID }}
          BENTO_SECRET_KEY: ${{ secrets.BENTO_SECRET_KEY }}
          BENTO_PUBLISHABLE_KEY: ${{ secrets.BENTO_PUBLISHABLE_KEY }}
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
      - name: Commit updated directory cache
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/utils/nomad_directory_cache.json
          git diff --cached --quiet || git commit -m "chore: update nomad directory cache [ci skip]"
          git push
      - name: Trigger deploy workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          token: ${{ secrets.GITHUB_TOKEN }}
