name: Sync Directory from Smart suite

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-directory]

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove cached distribution JSON
        run: rm -f src/utils/nomad_cache_table_6857167d82358a0f5e038c3f.json
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build project (regenerate cache)
        run: bun run build && bun format
        env:
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
      - name: Commit updated distribution cache
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/utils/nomad_cache_table_6857167d82358a0f5e038c3f.json
          git diff --cached --quiet || git commit -m "chore: update nomad distribution cache [ci skip]"
          git push
      - name: Trigger Deploy Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {}
            })
