name: Sync Events from Smart suite

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync_event]

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Update single record
        if: ${{ github.event.client_payload.record_id }}
        run: node scripts/update-single-record.js
        env:
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
          RECORD_ID: ${{ github.event.client_payload.record_id }}
          REPORT_ID: "655f749c8779ef70a3a1735e"
      - name: Update all records
        if: ${{ !github.event.client_payload.record_id }}
        run: node scripts/update-all-records.js
        env:
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
          REPORT_ID: "655f749c8779ef70a3a1735e"
      - name: Commit updated events cache
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/utils/nomad_cache_table_655f749c8779ef70a3a1735e.json
          git add src/utils/nomad_cache_table_global.json
          if [ "${{ github.event.client_payload.record_id }}" ]; then
            git diff --cached --quiet || git commit -m "chore: update nomad events record ${{ github.event.client_payload.record_id }} [ci skip]"
          else
            git diff --cached --quiet || git commit -m "chore: update nomad events cache [ci skip]"
          fi
          git push
