name: Sync Events from Smart suite

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync_event]

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove cached events JSON
        run: rm -f src/utils/nomad_cache_table_655f749c8779ef70a3a1735e.json
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build project (regenerate cache)
        run: bun run build
        env:
          SMART_SUITE_APIKEY: ${{ secrets.SMART_SUITE_APIKEY }}
          SMART_SUITE_ACCOUNT_ID: ${{ secrets.SMART_SUITE_ACCOUNT_ID }}
          SMART_SUITE_TABLE_ID_COMPANY: ${{ secrets.SMART_SUITE_TABLE_ID_COMPANY }}
      - name: Commit updated events cache
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/utils/nomad_cache_table_655f749c8779ef70a3a1735e.json
          git diff --cached --quiet || git commit -m "chore: update nomad events cache [ci skip]"
          git push
      - name: Trigger deploy workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          token: ${{ secrets.GITHUB_TOKEN }}
